#!/usr/bin/env bash
# Interactive picker for which AlgoJob services to clone and start.
#
#   ./configure.sh          walk through prompts, write services.conf
#   ./configure.sh --list   print the current selection and exit
#
# Writes services.conf (gitignored — a per-machine preference, like .env).
# clone.sh and start.sh both read it; if it's missing they fall back to
# services.conf.example (clone/start everything), so existing workflows are
# unaffected until you opt in here.
set -uo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

CONF="services.conf"

# label|VAR
SERVICES=(
  "algojobs-service (AI HR Service)|START_ALGOJOBS_SERVICE"
  "apex (AlgoApex assessment)|START_APEX"
  "personalized (content generation)|START_PERSONALIZED"
  "nest (backend API)|START_NEST"
  "frontend (web UI)|START_FRONTEND"
  "agent-server (LiveKit interview agent worker)|START_AGENT_SERVER"
)

# $1 = VAR name; prints its existing value from services.conf, defaulting to 1
# (services.conf.example's default) if unset or the file doesn't exist yet.
current_value() {
  local var="$1"
  if [ -f "$CONF" ]; then
    local v
    v="$(grep -E "^${var}=" "$CONF" | tail -1 | cut -d= -f2)"
    [ -n "$v" ] && { echo "$v"; return; }
  fi
  echo 1
}

if [ "${1:-}" = "--list" ]; then
  if [ ! -f "$CONF" ]; then
    echo "No $CONF yet — everything clones/starts by default. Run ./configure.sh to customize."
    exit 0
  fi
  cat "$CONF"
  exit 0
fi

echo "AlgoJob service selection"
echo "These 6 repos are always cloned and built into the shared Docker image"
echo "regardless of your answers below — the app services all share one image,"
echo "so the build needs every one of them present. This only controls which"
echo "containers ./start.sh actually launches."
echo

# No associative arrays here — bash 3.2 (macOS's default /bin/bash) doesn't
# support `declare -A`. Each VAR name is used directly as a variable via
# printf -v (write) / ${!var} (indirect read), both bash-3.2-safe.
for entry in "${SERVICES[@]}"; do
  IFS='|' read -r label var <<<"$entry"
  default="$(current_value "$var")"
  prompt_default="Y/n"
  [ "$default" = "0" ] && prompt_default="y/N"
  read -r -p "Start $label [$prompt_default] " ans
  if [ -z "$ans" ]; then
    ans="$([ "$default" = "1" ] && echo y || echo n)"
  fi
  case "$ans" in
    y|Y) printf -v "$var" '1' ;;
    *) printf -v "$var" '0' ;;
  esac
done

if [ "${START_FRONTEND}" = "1" ] && [ "${START_NEST}" != "1" ]; then
  echo
  echo "frontend depends_on nest at the compose level (docker-compose.yml) — enabling nest too."
  START_NEST=1
fi

echo
proctoring_default="$(current_value CLONE_PROCTORING)"
proctoring_prompt="y/N"
[ "$proctoring_default" = "1" ] && proctoring_prompt="Y/n"
read -r -p "Also clone algojob-proctoring-mise? (native-only — not part of the Docker build) [$proctoring_prompt] " proc_ans
if [ -z "$proc_ans" ]; then
  proc_ans="$([ "$proctoring_default" = "1" ] && echo y || echo n)"
fi
proc_val=0
case "$proc_ans" in y|Y) proc_val=1 ;; esac

{
  echo "# services.conf — which services ./start.sh launches, generated by ./configure.sh."
  echo "# Edit by hand (1 = on, 0 = off) or re-run ./configure.sh. Gitignored — this is"
  echo "# a per-machine preference, not shared config."
  echo "#"
  echo "# All six repos below are ALWAYS cloned and built into the shared Docker image"
  echo "# (docker-compose.yml's app services all share algojob-stack:latest) — these"
  echo "# flags only control which of their containers ./start.sh actually starts."
  for entry in "${SERVICES[@]}"; do
    IFS='|' read -r _ var <<<"$entry"
    echo "${var}=${!var}"
  done
  echo
  echo "# 1 = clone algojob-proctoring-mise too (native/dev.sh only — excluded from the"
  echo "# Docker build, see Dockerfile's py-build stage note), 0 = skip it."
  echo "CLONE_PROCTORING=${proc_val}"
} > "$CONF"

echo
echo "Wrote $CONF:"
cat "$CONF"

echo
read -r -p "Run ./clone.sh now? [Y/n] " do_clone
if [ "${do_clone:-y}" != "n" ] && [ "${do_clone:-y}" != "N" ]; then
  ./clone.sh
fi

echo
read -r -p "Build the shared Docker image now? (./start.sh --build) [Y/n] " do_build
if [ "${do_build:-y}" != "n" ] && [ "${do_build:-y}" != "N" ]; then
  ./start.sh --build
fi

echo
read -r -p "Start the selected services now with ./start.sh? [Y/n] " do_start
if [ "${do_start:-y}" != "n" ] && [ "${do_start:-y}" != "N" ]; then
  ./start.sh
fi
