#!/usr/bin/env bash
# One-way mirror of SVAR question audio: real S3 -> local MinIO.
#
# Question audio (TTS output for repeat_sentence / listening_comprehension) is
# generated by apex and its URL is stored in Neon's question_bank.audio_url,
# pointing at the real S3 bucket. Local dev writes candidate answer audio to
# MinIO instead, but never has a copy of the question audio to play back.
# The local MinIO bucket shares the real bucket's name (algojobterraformstate),
# so mirroring the question-audio prefixes here makes existing Neon rows
# resolve locally with zero code changes: audio_url is still the AWS-shaped
# URL, but the key underneath it now also exists in MinIO.
#
# Candidate answer recordings (apex-audio/, audio/<user_id>/) are deliberately
# NOT mirrored -- they're PII and are produced locally anyway.
#
# This script only ever reads from the real bucket and writes to MinIO. There
# is no reverse mode.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUCKET="algojobterraformstate"
AUDIO_PREFIX="algoapex/audio"
SECTIONS=(repeat_sentence listening_comprehension)
MC_IMAGE="minio/mc:RELEASE.2025-04-16T18-13-26Z"

DRY_RUN=false
ASSUME_YES=false
NEWER_THAN=""
CUSTOM_SECTIONS=()

usage() {
  cat <<'EOF'
Usage: scripts/sync-audio-to-minio.sh [options]

Mirrors SVAR question audio (repeat_sentence, listening_comprehension) from
the real S3 bucket into the local MinIO instance, so question_bank.audio_url
rows already in Neon resolve locally without any code changes.

Options:
  --section <name>   Mirror only this section prefix (repeatable). Defaults
                      to repeat_sentence and listening_comprehension.
  --newer-than <dur> Only mirror objects modified within <dur> (e.g. 30d),
                      passed straight through to `mc mirror --newer-than`.
  --dry-run           Show what would be copied without copying it.
  --yes                Skip the confirmation prompt.
  -h, --help           Show this help.

Credentials:
  Real S3 (read-only): AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY, sourced from
    the environment or apex-assessment/.env.
  MinIO (write): MINIO_ROOT_USER / MINIO_ROOT_PASSWORD, sourced from the
    environment or the repo root .env, defaulting to minioadmin/minioadmin.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --section)
      CUSTOM_SECTIONS+=("$2")
      shift 2
      ;;
    --newer-than)
      NEWER_THAN="$2"
      shift 2
      ;;
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    --yes)
      ASSUME_YES=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ ${#CUSTOM_SECTIONS[@]} -gt 0 ]]; then
  SECTIONS=("${CUSTOM_SECTIONS[@]}")
fi

# Pull a var out of a .env-style file without sourcing it (avoids executing
# arbitrary file content).
read_env_var() {
  local file="$1" key="$2"
  [[ -f "$file" ]] || return 0
  grep -E "^${key}=" "$file" | tail -n1 | cut -d= -f2- | sed -e 's/^"//' -e 's/"$//'
}

AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID:-$(read_env_var "$REPO_ROOT/apex-assessment/.env" AWS_ACCESS_KEY_ID)}"
AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY:-$(read_env_var "$REPO_ROOT/apex-assessment/.env" AWS_SECRET_ACCESS_KEY)}"
AWS_REGION="${AWS_REGION:-$(read_env_var "$REPO_ROOT/apex-assessment/.env" AWS_REGION)}"
AWS_REGION="${AWS_REGION:-ap-south-1}"

MINIO_ROOT_USER="${MINIO_ROOT_USER:-$(read_env_var "$REPO_ROOT/.env" MINIO_ROOT_USER)}"
MINIO_ROOT_PASSWORD="${MINIO_ROOT_PASSWORD:-$(read_env_var "$REPO_ROOT/.env" MINIO_ROOT_PASSWORD)}"
MINIO_ROOT_USER="${MINIO_ROOT_USER:-minioadmin}"
MINIO_ROOT_PASSWORD="${MINIO_ROOT_PASSWORD:-minioadmin}"
MINIO_URL="${MINIO_URL:-http://localhost:9000}"

if [[ -z "$AWS_ACCESS_KEY_ID" || -z "$AWS_SECRET_ACCESS_KEY" ]]; then
  echo "error: real AWS credentials not found (AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY)." >&2
  echo "Set them in the environment or in apex-assessment/.env." >&2
  exit 1
fi

# Prefer a host-installed `mc` (reliable networking on every platform). Fall
# back to the pinned image minio-init already uses, reaching the MinIO port
# published on the host via host.docker.internal (works on macOS/Windows
# Docker Desktop, and on Linux via --add-host=host.docker.internal:host-gateway).
# The real-S3 leg always goes out over the normal internet, so it needs no
# special networking either way.
if command -v mc >/dev/null 2>&1; then
  USE_HOST_MC=true
else
  USE_HOST_MC=false
  if ! command -v docker >/dev/null 2>&1; then
    echo "error: neither 'mc' nor 'docker' found on PATH." >&2
    echo "Install mc (e.g. 'brew install minio/stable/mc') or Docker, then retry." >&2
    exit 1
  fi
fi

LOCAL_MC_HOST="${MINIO_URL#http://}"
LOCAL_MC_HOST="${LOCAL_MC_HOST#https://}"
if [[ "$USE_HOST_MC" == false ]]; then
  LOCAL_MC_HOST="${LOCAL_MC_HOST/localhost/host.docker.internal}"
  LOCAL_MC_HOST="${LOCAL_MC_HOST/127.0.0.1/host.docker.internal}"
fi

run_mc() {
  if [[ "$USE_HOST_MC" == true ]]; then
    MC_HOST_prod="https://${AWS_ACCESS_KEY_ID}:${AWS_SECRET_ACCESS_KEY}@s3.${AWS_REGION}.amazonaws.com" \
    MC_HOST_local="http://${MINIO_ROOT_USER}:${MINIO_ROOT_PASSWORD}@${LOCAL_MC_HOST}" \
      mc "$@"
    return
  fi
  docker run --rm -i --add-host=host.docker.internal:host-gateway \
    -e "MC_HOST_prod=https://${AWS_ACCESS_KEY_ID}:${AWS_SECRET_ACCESS_KEY}@s3.${AWS_REGION}.amazonaws.com" \
    -e "MC_HOST_local=http://${MINIO_ROOT_USER}:${MINIO_ROOT_PASSWORD}@${LOCAL_MC_HOST}" \
    "$MC_IMAGE" "$@"
}

echo "== Sizing question audio prefixes on the real bucket =="
for section in "${SECTIONS[@]}"; do
  echo "-- ${AUDIO_PREFIX}/${section}/ --"
  run_mc du "prod/${BUCKET}/${AUDIO_PREFIX}/${section}/" || true
done

if [[ "$DRY_RUN" == false && "$ASSUME_YES" == false ]]; then
  read -r -p "Mirror the above into local MinIO (${BUCKET})? [y/N] " reply
  if [[ ! "$reply" =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 1
  fi
fi

MIRROR_FLAGS=(--overwrite)
if [[ "$DRY_RUN" == true ]]; then
  MIRROR_FLAGS+=(--dry-run)
fi
if [[ -n "$NEWER_THAN" ]]; then
  MIRROR_FLAGS+=(--newer-than "$NEWER_THAN")
fi

for section in "${SECTIONS[@]}"; do
  src="prod/${BUCKET}/${AUDIO_PREFIX}/${section}/"
  dst="local/${BUCKET}/${AUDIO_PREFIX}/${section}/"
  echo "== Mirroring ${src} -> ${dst} =="
  run_mc mirror "${MIRROR_FLAGS[@]}" "$src" "$dst"
done

echo "Done."
